version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      frontend:
        aliases:
          - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    ports:
      - "5601:5601"
    networks:
      frontend:
        aliases:
          - kibana

networks:
  frontend:
